name: DPP-Core
version: 4.0.6.32
description: All DP-PLUGINS plugins require this plugin.
main: com.darksoldier1404.dppc.DPPCore
authors: [ DEAD_POOLIO_ ]
api-version: 1.20
softdepend:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - LuckPerms
  - WorldGuard
  - Vault

commands:
  dppc:
  dppca:
  dppcp:
