name: DPP-Core
version: 4.0.3.25
main: com.darksoldier1404.dppc.DPPCore
authors: [ DEAD_POOLIO_ ]
api-version: 1.16
loadbefore:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - LuckPerms

commands:
  dppc:
  dppca:
  dppcp:
