name: DPP-Core
version: 4.0.2.19
main: com.darksoldier1404.dppc.DPPCore
authors: [ DEAD_POOLIO_ ]
api-version: 1.16
loadbefore:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib

commands:
  dppc:
  dppca:
