name: DPP-Core
version: 4.0.3.24
main: com.darksoldier1404.dppc.DPPCore
authors: [ DEAD_POOLIO_ ]
api-version: 1.21
loadbefore:
  - Essentials
  - PlaceholderAPI
  - ProtocolLib
  - LuckPerms
commands:
  dppc:
  dppca:
  dppcp: