name: DPP-Core
on:
  push:
    branches:
      - master
jobs:
  gradle:
    #    runs-on: self-hosted
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          echo "workflow=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        env:
          REPO_PUBLIC: ${{ secrets.REPO_PUBLIC }}
          REPO_DPP: ${{ secrets.REPO_DPP }}
        run: ./gradlew jar

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './common/build/resources/main/plugin.yml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.

      - name: Set env
        run: echo "RELEASE_VERSION=${{ steps.yaml-data.outputs.data }}" >> $GITHUB_ENV

      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Release #${{ env.RELEASE_VERSION }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: jars/*.jar
          prerelease: false
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Publish
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          REPO_PUBLIC: ${{ secrets.REPO_PUBLIC }}
          REPO_DPP: ${{ secrets.REPO_DPP }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publishPluginPublicationToHangar --stacktrace
